### Verbo GET – listar
GET http://localhost:8000/cliente/0 HTTP/1.1

### Verbo POST - adicionar
POST http://localhost:8000/cliente/1 HTTP/1.1
content-type : application/json

{
    "nome" : "va ljlsadfjlksdjf",
    "cpf" : "01387897465",
    "telefone" : "49982345567",
    "compra_fiado" : 1,
    "dia_fiado" : 20,
    "senha" : "abc"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type : application/json

{
    "nome" : "ashduahsd ljlsadfjlksdjf",
    "cpf" : "01387897465",
    "telefone" : "49982345567",
    "compra_fiado" : 1,
    "dia_fiado" : 20,
    "senha" : "abc"
}